// redux is a store of state variables to be used across the app
import { createSlice, configureStore } from "@reduxjs/toolkit";


//creating a redux slice to handle login and logout change of state with the auth
const authSlice = createSlice ({
    name: "auth",
    initialState: {
        isLogin: false
    },
    reducers: {
        login(state){
            state.isLogin = true
        },
        logout(state){
            state.isLogin = false
        },
    },
});

export const auth= authSlice.actions

//exporting a reducer generated by the auth slice.
export const store = configureStore({ //taking an object as an argument with configuration options
    reducer: authSlice.reducer,
});